### ISSUE TITLE
error

### ISSUE THREAD

**Issue by parames3010** [enarjord/passivbot_futures#6]
Hello, I am just a beginner I've been testing backtest.py, but I'm running into problems. how can I fix this error?

![image](https://user-images.githubusercontent.com/8073243/104039318-d0ba0500-5208-11eb-836c-f169f0a0857f.png)

**Comment by enarjord** [comment]
hello,

thanks for your interest

apologies, the backtester isn't well documented

to use it i recommend installing jupyter notebook.  with it you can analyze results, plot trades etc.

otherwise, you can use the provided example settings

the error you got there was because of missing keyword args

try
python3 backtest.py exchange your_user_name n_days

it will launch a series of backtests with randomized settings, to find the optimal ones.

i updated the readme on github to explain a bit more

**Comment by parames3010** [comment]
this command work “python backtest.py binance test_user 5” but still have some error.

![A1D0CE29-753A-42CD-9D49-C9786987DAD6](https://user-images.githubusercontent.com/8073243/104116280-ac197680-5349-11eb-92fe-0114f7eabb8f.jpeg)

**Comment by enarjord** [comment]
apologies, binance backtesting doesn't work at the moment

i have been backtesting using only bybit lately and neglected binance support

i do not recommend using binance right now because of their minimum contract size being 0.001 btc ~= 40 usdt

bybit in comparison has 1 usd minimum

you need 40x as much margin in binance as in bybit for the same behavior, so it's not practical with such an experimental bot as this.  in future I might focus more on binance

**Comment by parames3010** [comment]
Thank you very much, interesting for the 1 usd minimum, it's a great opportunity for me to try it out on Bybit.

**Comment by enarjord** [comment]
if you don't have an account on bybit yet, feel free to use my ref:

https://www.bybit.com/app/register?ref=PQEGz
